name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.template.SomeCoolPlugin
description: 'A cool plugin'
authors: ['V7Zeee']
contributors: []
website: ${WEBSITE}

depend: []
libraries:
  - 'org.projectlombok:lombok:${LOMBOK_VERSION}'

commands:
  coolplugin:
    description: General command of the coolest plugin ever
    usage: /coolplugin

